from __future__ import annotations

from typing import Any

from fastapi import APIRouter, Request

router = APIRouter(tags=["discovery"])


@router.get("/.well-known/agent-manifest.json", include_in_schema=False)
def agent_manifest(request: Request) -> dict[str, Any]:
    base_url = str(request.base_url).rstrip("/")
    profile = request.app.state.profile
    active_routers = set(profile["router_names"])
    tool_catalog = [
        {
            "router": "runs",
            "name": "runs.latest",
            "method": "GET",
            "path": "/runs/latest",
            "description": "Retrieve the latest completed ingestion run and its quality audits.",
        },
        {
            "router": "freshness",
            "name": "freshness.index",
            "method": "GET",
            "path": "/freshness",
            "description": "Report canonical data coverage, freshness, and quality status for trust badges.",
        },
        {
            "router": "freshness",
            "name": "freshness.ticker",
            "method": "GET",
            "path": "/freshness/{ticker}",
            "description": "Report ticker-level source freshness and quality metadata.",
        },
        {
            "router": "documents",
            "name": "documents.current",
            "method": "GET",
            "path": "/documents/current",
            "description": "List the newest raw artifacts for retrieval-augmented workflows.",
        },
        {
            "router": "market",
            "name": "market.company_profile",
            "method": "GET",
            "path": "/companies/{ticker}",
            "description": "Retrieve a canonical company profile with freshness and lineage metadata.",
        },
        {
            "router": "market",
            "name": "market.quote_snapshot",
            "method": "GET",
            "path": "/quotes/{ticker}",
            "description": "Retrieve the latest processed quote snapshot for a ticker.",
        },
        {
            "router": "market",
            "name": "market.financial_ratios",
            "method": "GET",
            "path": "/ratios/{ticker}",
            "description": "Retrieve processed ratio rows for a ticker and optional period.",
        },
        {
            "router": "market",
            "name": "market.events",
            "method": "GET",
            "path": "/events/{ticker}",
            "description": "Retrieve processed company event rows.",
        },
        {
            "router": "market",
            "name": "market.peers",
            "method": "GET",
            "path": "/peers/{ticker}",
            "description": "Retrieve processed listed peer relationships.",
        },
        {
            "router": "market",
            "name": "market.screen",
            "method": "POST",
            "path": "/screen",
            "description": "Screen companies using canonical profile, quote, and ratio filters.",
        },
        {
            "router": "screeners",
            "name": "screeners.create",
            "method": "POST",
            "path": "/screeners",
            "description": "Persist a reusable stock screener strategy from canonical market-data filters.",
        },
        {
            "router": "screeners",
            "name": "screeners.show",
            "method": "GET",
            "path": "/screeners/{screener_id}",
            "description": "Return a saved screener and recent evaluation history.",
        },
        {
            "router": "screeners",
            "name": "screeners.evaluate",
            "method": "POST",
            "path": "/screeners/{screener_id}/evaluate",
            "description": "Evaluate a saved screener and persist result-count/top-ticker history.",
        },
        {
            "router": "portfolios",
            "name": "portfolios.create",
            "method": "POST",
            "path": "/portfolios",
            "description": "Create or update a portfolio for holdings analysis and customer X-ray workflows.",
        },
        {
            "router": "portfolios",
            "name": "portfolios.show",
            "method": "GET",
            "path": "/portfolios/{portfolio_id}",
            "description": "Return holdings enriched with canonical company, quote, ratio, and P/L data.",
        },
        {
            "router": "portfolios",
            "name": "portfolios.add_holding",
            "method": "POST",
            "path": "/portfolios/{portfolio_id}/holdings",
            "description": "Add or update a portfolio holding.",
        },
        {
            "router": "portfolios",
            "name": "portfolios.xray",
            "method": "GET",
            "path": "/portfolios/{portfolio_id}/xray",
            "description": "Return portfolio value, concentration, sector exposure, and unrealized P/L analytics.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.create",
            "method": "POST",
            "path": "/watchlists",
            "description": "Create or update a saved watchlist for dashboards, alerts, and agent digests.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.show",
            "method": "GET",
            "path": "/watchlists/{watchlist_id}",
            "description": "Return watchlist items enriched with canonical company, quote, and ratio data.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.add_item",
            "method": "POST",
            "path": "/watchlists/{watchlist_id}/items",
            "description": "Add a ticker to a watchlist.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.add_alert_rule",
            "method": "POST",
            "path": "/watchlists/{watchlist_id}/alerts",
            "description": "Create a price, market-cap, or ratio alert rule for a watchlist.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.list_alert_rules",
            "method": "GET",
            "path": "/watchlists/{watchlist_id}/alerts",
            "description": "List active or disabled alert rules, optionally including per-rule review summaries or needs_attention=true filtering.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.update_alert_rule",
            "method": "PATCH",
            "path": "/watchlists/{watchlist_id}/alerts/{rule_id}",
            "description": "Update an alert rule threshold, operator, cooldown, ticker, metric, or enabled state.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.disable_alert_rule",
            "method": "DELETE",
            "path": "/watchlists/{watchlist_id}/alerts/{rule_id}",
            "description": "Disable an alert rule without deleting its historical alert events.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.evaluate_alerts",
            "method": "GET",
            "path": "/watchlists/{watchlist_id}/alerts/evaluate",
            "description": "Evaluate saved price, market-cap, or ratio alert rules with per-rule notification cooldowns.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.owner_alert_evaluation_readiness",
            "method": "GET",
            "path": "/watchlists/alerts/readiness",
            "description": "Aggregate alert readiness across every watchlist for an owner, including blocked missing, stale, quality, and data-rights counts.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.owner_alert_readiness_actions",
            "method": "GET",
            "path": "/watchlists/alerts/readiness/actions",
            "description": "Return prioritized remediation actions for owner-level alert readiness blockers.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.save_owner_alert_readiness_action_queue",
            "method": "POST",
            "path": "/watchlists/alerts/readiness/action-queue",
            "description": "Persist owner-level alert readiness remediation actions as a saved advisor action queue.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.alert_evaluation_readiness",
            "method": "GET",
            "path": "/watchlists/{watchlist_id}/alerts/readiness",
            "description": "Summarize whether active alert rules have the local market data needed for trustworthy evaluation.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.alert_events",
            "method": "GET",
            "path": "/watchlists/{watchlist_id}/alerts/events",
            "description": "Read durable alert trigger events, optionally filtered by review_status=open, reviewed, or dismissed.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.alert_event_review_summary",
            "method": "GET",
            "path": "/watchlists/{watchlist_id}/alerts/events/summary",
            "description": "Summarize open, reviewed, and dismissed alert event counts for a watchlist.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.review_alert_event",
            "method": "PATCH",
            "path": "/watchlists/{watchlist_id}/alerts/events/{event_id}",
            "description": "Mark a durable alert event as open, reviewed, or dismissed with reviewer notes.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.bulk_review_alert_events",
            "method": "PATCH",
            "path": "/watchlists/{watchlist_id}/alerts/events/bulk",
            "description": "Bulk mark explicit or filtered alert events as open, reviewed, or dismissed with reviewer notes.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.alert_event_review_history",
            "method": "GET",
            "path": "/watchlists/{watchlist_id}/alerts/events/{event_id}/reviews",
            "description": "Read the append-only review status audit trail for a durable alert event.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.alert_review_audit_history",
            "method": "GET",
            "path": "/watchlists/{watchlist_id}/alerts/reviews",
            "description": "Search append-only alert review audit rows by event, rule, status, or source.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.alert_rule_events",
            "method": "GET",
            "path": "/watchlists/{watchlist_id}/alerts/{rule_id}/events",
            "description": "Read durable trigger history for a single watchlist alert rule, optionally filtered by review_status.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.alert_rule_event_review_summary",
            "method": "GET",
            "path": "/watchlists/{watchlist_id}/alerts/{rule_id}/events/summary",
            "description": "Summarize open, reviewed, and dismissed alert event counts for a single alert rule.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.webhook_subscriptions",
            "method": "GET",
            "path": "/watchlists/webhooks/subscriptions",
            "description": "List active customer webhook destinations for alert trigger events.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.create_webhook_subscription",
            "method": "POST",
            "path": "/watchlists/webhooks/subscriptions",
            "description": "Register or re-enable a customer webhook destination with optional HMAC signing for alert trigger events.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.update_webhook_subscription",
            "method": "PATCH",
            "path": "/watchlists/webhooks/subscriptions/{subscription_id}",
            "description": "Update a customer webhook destination, enabled state, event type, or signing secret.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.disable_webhook_subscription",
            "method": "DELETE",
            "path": "/watchlists/webhooks/subscriptions/{subscription_id}",
            "description": "Disable a customer webhook subscription without deleting its delivery history.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.test_webhook_subscription",
            "method": "POST",
            "path": "/watchlists/webhooks/subscriptions/{subscription_id}/test",
            "description": "Queue a signed test webhook event so customers can verify a destination before real alerts fire.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.webhook_status",
            "method": "GET",
            "path": "/watchlists/webhooks/status",
            "description": "Summarize webhook subscription health, pending delivery pressure, and recent delivery problems.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.webhook_outbox",
            "method": "GET",
            "path": "/watchlists/webhooks/outbox",
            "description": "Read pending destination-specific webhook outbox rows created from alert trigger events.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.replay_webhook_outbox",
            "method": "POST",
            "path": "/watchlists/webhooks/outbox/{outbox_id}/replay",
            "description": "Requeue a failed or pending webhook outbox row for immediate redelivery after endpoint repair.",
        },
        {
            "router": "watchlists",
            "name": "watchlists.webhook_deliveries",
            "method": "GET",
            "path": "/watchlists/webhooks/deliveries",
            "description": "Inspect webhook delivery attempts, HTTP statuses, retry state, and errors.",
        },
        {
            "router": "vectors",
            "name": "vectors.search",
            "method": "GET",
            "path": "/vectors/search",
            "description": "Search locally embedded documents with TurboVec when available.",
        },
        {
            "router": "vectors",
            "name": "vectors.rebuild",
            "method": "POST",
            "path": "/vectors/rebuild",
            "description": "Rebuild the local semantic index for a completed run.",
        },
        {
            "router": "agents",
            "name": "agents.advisor_workbench",
            "method": "GET",
            "path": "/agents/advisor-workbench",
            "description": "Rank saved advisor action queue tasks into a next-best-action workbench.",
        },
        {
            "router": "agents",
            "name": "agents.advisor_outreach_draft",
            "method": "POST",
            "path": "/agents/advisor-outreach-draft",
            "description": "Turn a saved advisor action queue task into reviewable customer outreach copy and optionally save it.",
        },
        {
            "router": "agents",
            "name": "agents.advisor_outreach_drafts",
            "method": "GET",
            "path": "/agents/advisor-outreach-drafts",
            "description": "List saved advisor outreach drafts by owner and review status.",
        },
        {
            "router": "agents",
            "name": "agents.advisor_outreach_draft.show",
            "method": "GET",
            "path": "/agents/advisor-outreach-drafts/{draft_id}",
            "description": "Fetch a saved advisor outreach draft with review metadata.",
        },
        {
            "router": "agents",
            "name": "agents.advisor_outreach_draft.review",
            "method": "PATCH",
            "path": "/agents/advisor-outreach-drafts/{draft_id}",
            "description": "Update advisor outreach draft review status, notes, and reviewer with compliance-gated approval.",
        },
        {
            "router": "agents",
            "name": "agents.advisor_outreach_draft.compliance_review",
            "method": "POST",
            "path": "/agents/advisor-outreach-drafts/{draft_id}/compliance-review",
            "description": "Review a saved advisor outreach draft for compliance issues and optionally save the audit result.",
        },
        {
            "router": "agents",
            "name": "agents.advisor_outreach_draft.compliance_reviews",
            "method": "GET",
            "path": "/agents/advisor-outreach-drafts/{draft_id}/compliance-reviews",
            "description": "List saved compliance review audit records for an advisor outreach draft.",
        },
        {
            "router": "agents",
            "name": "agents.advisor_outreach_draft.delivery_packet",
            "method": "POST",
            "path": "/agents/advisor-outreach-drafts/{draft_id}/delivery-packet",
            "description": "Build a customer-ready outreach packet and optionally save a delivery record.",
        },
        {
            "router": "agents",
            "name": "agents.advisor_outreach_delivery_dashboard",
            "method": "GET",
            "path": "/agents/advisor-outreach-delivery-dashboard",
            "description": "Summarize ready, stale, delivered, voided, and missing outreach delivery packets for an owner.",
        },
        {
            "router": "agents",
            "name": "agents.customer_intent_dashboard",
            "method": "GET",
            "path": "/agents/customer-intent-dashboard",
            "description": "Rank customers by saved outreach outcomes, pending outcome capture, and next compliant follow-up action.",
        },
        {
            "router": "agents",
            "name": "agents.customer_engagement_timeline",
            "method": "GET",
            "path": "/agents/customer-engagement-timeline",
            "description": "Return a chronological owner timeline across outreach drafts, compliance reviews, deliveries, and outcomes.",
        },
        {
            "router": "agents",
            "name": "agents.customer_engagement_brief",
            "method": "GET",
            "path": "/agents/customer-engagement-brief",
            "description": "Summarize owner engagement history into current intent, next action, talking points, avoid-list, and evidence references.",
        },
        {
            "router": "agents",
            "name": "agents.customer_engagement_cadence_review",
            "method": "GET",
            "path": "/agents/customer-engagement-cadence-review",
            "description": "Review whether customer contact is appropriate now and return cadence blockers, next route, and guardrails.",
        },
        {
            "router": "agents",
            "name": "agents.customer_engagement_cadence_dashboard",
            "method": "GET",
            "path": "/agents/customer-engagement-cadence-dashboard",
            "description": "Rank owners by cadence readiness, blockers, current intent, and next route across the advisor book.",
        },
        {
            "router": "agents",
            "name": "agents.customer_engagement_action_queue",
            "method": "GET",
            "path": "/agents/customer-engagement-action-queue",
            "description": "Convert book-level cadence readiness into executable advisor tasks with evidence, routes, and guardrails.",
        },
        {
            "router": "agents",
            "name": "agents.customer_engagement_task_brief",
            "method": "GET",
            "path": "/agents/customer-engagement-task-brief",
            "description": "Turn a queued customer engagement task into an execution brief with talk track, proof points, guardrails, and completion criteria.",
        },
        {
            "router": "agents",
            "name": "agents.ai_recommendation_effectiveness_dashboard",
            "method": "GET",
            "path": "/agents/ai-recommendation-effectiveness-dashboard",
            "description": "Measure which AI-guided outreach recommendations convert into captured customer outcomes and positive signals.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_backlog",
            "method": "GET",
            "path": "/agents/ai-improvement-backlog",
            "description": "Turn recommendation effectiveness evidence into ranked AI improvement work with success metrics and guardrails.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_experiment_plan",
            "method": "GET",
            "path": "/agents/ai-improvement-experiment-plan",
            "description": "Convert the top AI improvement backlog item into a measurable experiment with baseline, treatment, metrics, and stop conditions.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_experiment_launch_packet",
            "method": "GET",
            "path": "/agents/ai-improvement-experiment-launch-packet",
            "description": "Package an AI improvement experiment into launch readiness, cohort rules, checklist, data capture, and rollback criteria.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_experiment_readout",
            "method": "GET",
            "path": "/agents/ai-improvement-experiment-readout",
            "description": "Summarize experiment metrics against launch criteria and recommend continue, ship, rollback, or more evidence.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_rollout_readiness",
            "method": "GET",
            "path": "/agents/ai-improvement-rollout-readiness",
            "description": "Translate experiment readout into a rollout gate, phases, customer impact, monitoring plan, and rollback triggers.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_rollout_monitor",
            "method": "GET",
            "path": "/agents/ai-improvement-rollout-monitor",
            "description": "Monitor AI improvement rollout status, alerts, tracked metrics, rollback risk, and immediate next action.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_release_packet",
            "method": "GET",
            "path": "/agents/ai-improvement-release-packet",
            "description": "Package rollout monitor state into customer impact, advisor enablement, risks, support talking points, and rollback guidance.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_adoption_playbook",
            "method": "GET",
            "path": "/agents/ai-improvement-adoption-playbook",
            "description": "Turn an AI improvement release packet into advisor adoption tasks, training checks, customer language, blockers, and success signals.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_adoption_monitor",
            "method": "GET",
            "path": "/agents/ai-improvement-adoption-monitor",
            "description": "Monitor advisor adoption readiness, training status, customer-language safety, blockers, success signals, and immediate next action.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_adoption_impact_ledger",
            "method": "GET",
            "path": "/agents/ai-improvement-adoption-impact-ledger",
            "description": "Tie AI adoption to customer impact, advisor usage, blocked accounts, proof points, and the scale decision.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_scale_decision_packet",
            "method": "GET",
            "path": "/agents/ai-improvement-scale-decision-packet",
            "description": "Convert measured AI adoption impact into a scale, pilot, hold, or evidence-collection decision with customer proof and advisor-change guidance.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_scale_execution_plan",
            "method": "GET",
            "path": "/agents/ai-improvement-scale-execution-plan",
            "description": "Turn an AI scale decision into accountable rollout tasks, guardrails, customer-proof checks, acceptance criteria, escalation, and next action.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_scale_execution_monitor",
            "method": "GET",
            "path": "/agents/ai-improvement-scale-execution-monitor",
            "description": "Monitor AI scale execution progress, guardrails, customer proof, acceptance gaps, blockers, risk, and immediate owner action.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_scale_learning_report",
            "method": "GET",
            "path": "/agents/ai-improvement-scale-learning-report",
            "description": "Convert AI scale execution monitoring into validated learnings, open questions, feedback actions, roadmap updates, and the next improvement candidate.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_roadmap_refresh",
            "method": "GET",
            "path": "/agents/ai-improvement-roadmap-refresh",
            "description": "Turn AI scale learnings into a backlog-ready roadmap item with priority, owner actions, evidence, acceptance gates, sequencing, and measurement plan.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_backlog_handoff",
            "method": "GET",
            "path": "/agents/ai-improvement-backlog-handoff",
            "description": "Package an AI roadmap refresh into an implementation-ready backlog handoff with story, scope, dependencies, acceptance gates, measurement, and launch readiness.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_implementation_kickoff_packet",
            "method": "GET",
            "path": "/agents/ai-improvement-implementation-kickoff-packet",
            "description": "Turn an AI backlog handoff into an implementation kickoff packet with engineering scope, QA gates, data contracts, customer guardrails, launch checklist, and immediate action.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_implementation_readiness_monitor",
            "method": "GET",
            "path": "/agents/ai-improvement-implementation-readiness-monitor",
            "description": "Monitor AI implementation readiness across QA gates, data contracts, customer guardrails, launch checklist, blockers, risk, and immediate owner action.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_implementation_blocker_resolution_plan",
            "method": "GET",
            "path": "/agents/ai-improvement-implementation-blocker-resolution-plan",
            "description": "Convert implementation readiness blockers into owned remediation tasks with proof required, exit criteria, QA rerun plan, guardrail clearance, and unblock action.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_implementation_unblock_verification_report",
            "method": "GET",
            "path": "/agents/ai-improvement-implementation-unblock-verification-report",
            "description": "Verify implementation unblock readiness across remediation tasks, proof, exit criteria, QA reruns, customer guardrails, and next verification action.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_implementation_qa_review_packet",
            "method": "GET",
            "path": "/agents/ai-improvement-implementation-qa-review-packet",
            "description": "Package implementation QA scope, evidence gaps, test gates, customer guardrails, signoff requirements, and next QA action.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_implementation_qa_signoff_report",
            "method": "GET",
            "path": "/agents/ai-improvement-implementation-qa-signoff-report",
            "description": "Produce an implementation QA signoff decision with required signoffs, evidence gaps, launch blockers, guardrail state, and next signoff action.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_launch_review_packet",
            "method": "GET",
            "path": "/agents/ai-improvement-launch-review-packet",
            "description": "Turn QA signoff into a final AI launch or hold packet with scope, customer guardrails, monitoring requirements, rollback triggers, blockers, and next launch action.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_launch_execution_plan",
            "method": "GET",
            "path": "/agents/ai-improvement-launch-execution-plan",
            "description": "Convert an AI launch review decision into owned launch or hold tasks, monitoring setup, rollback setup, customer guardrails, exit criteria, and immediate action.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_launch_execution_monitor",
            "method": "GET",
            "path": "/agents/ai-improvement-launch-execution-monitor",
            "description": "Monitor AI launch execution progress, monitoring setup, rollback readiness, exit criteria, blockers, risk, and immediate owner action.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_launch_outcome_monitor",
            "method": "GET",
            "path": "/agents/ai-improvement-launch-outcome-monitor",
            "description": "Track post-launch customer-value readiness, customer signals, rollback readiness, blockers, risk, and the next owner action for an AI improvement launch.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_launch_value_proof_packet",
            "method": "GET",
            "path": "/agents/ai-improvement-launch-value-proof-packet",
            "description": "Package launch outcome state into customer-value claimability, proof points, evidence gaps, customer-safe language, risk, and advisor next action.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_launch_customer_communication_packet",
            "method": "GET",
            "path": "/agents/ai-improvement-launch-customer-communication-packet",
            "description": "Turn launch value proof into customer-safe advisor communication, audience visibility, review gates, blocked claims, and next action.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_launch_customer_communication_review_packet",
            "method": "GET",
            "path": "/agents/ai-improvement-launch-customer-communication-review-packet",
            "description": "Review customer communication for send or hold decisions, required approvals, send blockers, escalation path, approved copy, and advisor next action.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_launch_customer_communication_delivery_packet",
            "method": "GET",
            "path": "/agents/ai-improvement-launch-customer-communication-delivery-packet",
            "description": "Convert reviewed customer communication into a delivery status, channel plan, payload, checklist, audit trail, follow-up plan, and next action.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_launch_customer_communication_delivery_monitor",
            "method": "GET",
            "path": "/agents/ai-improvement-launch-customer-communication-delivery-monitor",
            "description": "Monitor customer communication delivery progress, checklist blockers, audit status, follow-up state, risk, and immediate action.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_launch_customer_communication_delivery_unblock_plan",
            "method": "GET",
            "path": "/agents/ai-improvement-launch-customer-communication-delivery-unblock-plan",
            "description": "Convert blocked communication delivery monitoring into owner-specific unblock tasks, proof gates, exit criteria, recheck plan, and immediate action.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_launch_customer_communication_delivery_unblock_verification_report",
            "method": "GET",
            "path": "/agents/ai-improvement-launch-customer-communication-delivery-unblock-verification-report",
            "description": "Verify blocked communication delivery unblock work with proof results, failed checks, required follow-up, risk, and next action.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_launch_customer_communication_delivery_send_authorization_packet",
            "method": "GET",
            "path": "/agents/ai-improvement-launch-customer-communication-delivery-send-authorization-packet",
            "description": "Authorize or hold customer communication send after unblock verification with requirements, blocked reasons, payload status, risk, and next action.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_launch_customer_communication_delivery_send_authorization_monitor",
            "method": "GET",
            "path": "/agents/ai-improvement-launch-customer-communication-delivery-send-authorization-monitor",
            "description": "Monitor send authorization state, blocked requirements, blocked reasons, payload exposure, risk, and immediate action.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_launch_customer_communication_delivery_send_authorization_unblock_plan",
            "method": "GET",
            "path": "/agents/ai-improvement-launch-customer-communication-delivery-send-authorization-unblock-plan",
            "description": "Convert held send authorization into owner-specific unblock tasks, authorization gates, exit criteria, recheck plan, and immediate action.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_launch_customer_communication_delivery_send_authorization_unblock_verification_report",
            "method": "GET",
            "path": "/agents/ai-improvement-launch-customer-communication-delivery-send-authorization-unblock-verification-report",
            "description": "Verify send authorization unblock gates, exit criteria, unblock tasks, failed checks, required follow-up, risk, and next action.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_launch_customer_communication_delivery_send_readiness_packet",
            "method": "GET",
            "path": "/agents/ai-improvement-launch-customer-communication-delivery-send-readiness-packet",
            "description": "Package customer communication send readiness with send gate, customer claim status, blockers, advisor review, and immediate action.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_launch_customer_communication_delivery_send_readiness_review_packet",
            "method": "GET",
            "path": "/agents/ai-improvement-launch-customer-communication-delivery-send-readiness-review-packet",
            "description": "Review customer communication send readiness into send or hold decision, approvals, blockers, payload, and advisor next action.",
        },
        {
            "router": "agents",
            "name": "agents.ai_improvement_launch_customer_communication_delivery_send_execution_handoff_packet",
            "method": "GET",
            "path": "/agents/ai-improvement-launch-customer-communication-delivery-send-execution-handoff-packet",
            "description": "Convert send readiness review into operator-safe handoff status, execution gate, payload, audit trail, blockers, and immediate action.",
        },
        {
            "router": "agents",
            "name": "agents.customer_intent_action_plan",
            "method": "GET",
            "path": "/agents/customer-intent-action-plan",
            "description": "Convert ranked customer intent into a prioritized, evidence-backed advisor worklist.",
        },
        {
            "router": "agents",
            "name": "agents.customer_intent_followup_packet",
            "method": "GET",
            "path": "/agents/customer-intent-followup-packet",
            "description": "Turn the top customer-intent action into advisor instructions, reviewed-copy scaffolding, evidence, and guardrails.",
        },
        {
            "router": "agents",
            "name": "agents.customer_intent_followup_review",
            "method": "GET",
            "path": "/agents/customer-intent-followup-review",
            "description": "Review the top customer-intent follow-up packet for risky copy, evidence, review gates, and guardrails.",
        },
        {
            "router": "agents",
            "name": "agents.customer_intent_followup_draft",
            "method": "POST",
            "path": "/agents/customer-intent-followup-draft",
            "description": "Convert a passing customer-intent follow-up packet into a reviewable outreach draft and optionally save it.",
        },
        {
            "router": "agents",
            "name": "agents.advisor_outreach_deliveries",
            "method": "GET",
            "path": "/agents/advisor-outreach-deliveries",
            "description": "List saved outreach delivery records by owner and status.",
        },
        {
            "router": "agents",
            "name": "agents.advisor_outreach_delivery.show",
            "method": "GET",
            "path": "/agents/advisor-outreach-deliveries/{delivery_id}",
            "description": "Fetch a saved outreach delivery record with packet and compliance evidence.",
        },
        {
            "router": "agents",
            "name": "agents.advisor_outreach_delivery.update",
            "method": "PATCH",
            "path": "/agents/advisor-outreach-deliveries/{delivery_id}",
            "description": "Update outreach delivery record status, delivery notes, and delivered-by metadata.",
        },
        {
            "router": "agents",
            "name": "agents.advisor_outreach_delivery.outcome",
            "method": "POST",
            "path": "/agents/advisor-outreach-deliveries/{delivery_id}/outcome",
            "description": "Record a customer response outcome for a delivered outreach packet and recommend the next action.",
        },
        {
            "router": "agents",
            "name": "agents.advisor_outreach_outcomes",
            "method": "GET",
            "path": "/agents/advisor-outreach-outcomes",
            "description": "List saved customer response outcomes by owner, delivery, or outcome type.",
        },
        {
            "router": "agents",
            "name": "agents.advisor_outreach_outcome.show",
            "method": "GET",
            "path": "/agents/advisor-outreach-outcomes/{outcome_id}",
            "description": "Fetch a saved customer response outcome with its next-action recommendation.",
        },
        {
            "router": "agents",
            "name": "agents.action_queue",
            "method": "POST",
            "path": "/agents/action-queue",
            "description": "Convert advisor follow-up packs into trackable tasks and optionally save the queue.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.summary",
            "method": "GET",
            "path": "/agents/action-queues/summary",
            "description": "Summarize saved advisor action queues by status, focus, and urgency without returning task payloads.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks",
            "method": "GET",
            "path": "/agents/action-queues/tasks",
            "description": "List saved advisor action queue tasks with status, focus, urgency, assignee, due-date, and owner filters without returning full queue payloads.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.workload",
            "method": "GET",
            "path": "/agents/action-queues/tasks/workload",
            "description": "Summarize active saved advisor action queue workload by assignee and due-date bucket for team dashboards.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.summary",
            "method": "GET",
            "path": "/agents/action-queues/tasks/escalations/summary",
            "description": "Summarize saved advisor action queue escalations across the customer book or a single owner for manager dashboards.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.inbox",
            "method": "GET",
            "path": "/agents/action-queues/tasks/escalations/inbox",
            "description": "List only currently actionable saved task escalations, excluding resolved and future-snoozed manager reviews, with severity, inbox-status, assignee, and focus filters.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.inbox.notification",
            "method": "GET",
            "path": "/agents/action-queues/tasks/escalations/inbox/notification",
            "description": "Build a compact manager notification payload from the filtered escalation inbox without returning full task details.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.inbox.notification.log",
            "method": "POST",
            "path": "/agents/action-queues/tasks/escalations/inbox/notification",
            "description": "Persist an idempotent audit record for a prepared or sent escalation inbox notification payload.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.inbox.notification.logs",
            "method": "GET",
            "path": "/agents/action-queues/tasks/escalations/inbox/notification/logs",
            "description": "List persisted escalation inbox notification audit records by owner, channel, or status.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.inbox.notification.summary",
            "method": "GET",
            "path": "/agents/action-queues/tasks/escalations/inbox/notification/summary",
            "description": "Summarize escalation notification delivery health by status and channel with recent failures.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.inbox.notification.delivery_control_summary",
            "method": "GET",
            "path": "/agents/action-queues/tasks/escalations/inbox/notification/delivery-control-summary",
            "description": "Summarize queued deliveries, leases, dead letters, attempts, releases, and remediations for delivery operations.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.inbox.notification.delivery_queue",
            "method": "GET",
            "path": "/agents/action-queues/tasks/escalations/inbox/notification/delivery-queue",
            "description": "List failed and stale prepared escalation notification payloads that delivery workers should retry or send.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.inbox.notification.delivery_incident_summary",
            "method": "GET",
            "path": "/agents/action-queues/tasks/escalations/inbox/notification/delivery-incident-summary",
            "description": "Summarize escalation notification delivery incidents by actionable, resolved, and active snooze buckets for operational dashboards.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.inbox.notification.delivery_incident_workload",
            "method": "GET",
            "path": "/agents/action-queues/tasks/escalations/inbox/notification/delivery-incident-workload",
            "description": "Summarize unresolved delivery incident ownership by assignee and follow-up status for manager workload dashboards.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.inbox.notification.delivery_incidents",
            "method": "GET",
            "path": "/agents/action-queues/tasks/escalations/inbox/notification/delivery-incidents",
            "description": "List prioritized escalation notification delivery incidents across dead letters, claims, retries, and stale prepared sends with latest triage review context, assignee and follow-up drill-down filters, and resolved or active snooze suppression by default.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.inbox.notification.delivery_incidents.detail",
            "method": "GET",
            "path": "/agents/action-queues/tasks/escalations/inbox/notification/delivery-incidents/{notification_id}",
            "description": "Hydrate one active delivery incident with notification state, latest review, review history, delivery attempts, remediations, claim-release audit context, a chronological incident timeline, and deterministic operator next actions.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.inbox.notification.delivery_incidents.actions",
            "method": "POST",
            "path": "/agents/action-queues/tasks/escalations/inbox/notification/delivery-incidents/{notification_id}/actions",
            "description": "Execute a currently available delivery incident next action by action_id after server-side availability validation and return post-action incident state.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.inbox.notification.delivery_incident_reviews",
            "method": "GET",
            "path": "/agents/action-queues/tasks/escalations/inbox/notification/delivery-incident-reviews",
            "description": "List escalation notification delivery incident triage reviews by owner, notification, type, or status.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.inbox.notification.delivery_incident_reviews.bulk",
            "method": "POST",
            "path": "/agents/action-queues/tasks/escalations/inbox/notification/delivery-incident-reviews",
            "description": "Record the same acknowledgement, assignment, snooze, follow-up, or resolution across multiple delivery incidents atomically.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.inbox.notification.delivery_incidents.review",
            "method": "POST",
            "path": "/agents/action-queues/tasks/escalations/inbox/notification/delivery-incidents/{notification_id}/review",
            "description": "Record an acknowledgement, assignment, snooze, follow-up, or resolution for a delivery incident without mutating delivery state.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.inbox.notification.delivery_claims",
            "method": "GET",
            "path": "/agents/action-queues/tasks/escalations/inbox/notification/delivery-claims",
            "description": "List active, expiring, and expired escalation notification delivery leases for operational monitoring.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.inbox.notification.deadletters",
            "method": "GET",
            "path": "/agents/action-queues/tasks/escalations/inbox/notification/deadletters",
            "description": "List exhausted escalation notification deliveries with payload and dead-letter context for remediation.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.inbox.notification.deadletters.requeue",
            "method": "POST",
            "path": "/agents/action-queues/tasks/escalations/inbox/notification/deadletters/{notification_id}/requeue",
            "description": "Requeue an exhausted escalation notification after remediation while preserving delivery-attempt history.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.inbox.notification.deadletters.remediations",
            "method": "GET",
            "path": "/agents/action-queues/tasks/escalations/inbox/notification/deadletters/remediations",
            "description": "List operator remediation audit records for exhausted escalation notification dead letters.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.inbox.notification.delivery_attempts",
            "method": "GET",
            "path": "/agents/action-queues/tasks/escalations/inbox/notification/delivery-attempts",
            "description": "List immutable escalation notification delivery attempts by owner, notification, or outcome status.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.inbox.notification.delivery_claim_releases",
            "method": "GET",
            "path": "/agents/action-queues/tasks/escalations/inbox/notification/delivery-claim-releases",
            "description": "List audited escalation notification delivery claim releases by owner, notification, or releasing operator.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.inbox.notification.delivery_claim",
            "method": "POST",
            "path": "/agents/action-queues/tasks/escalations/inbox/notification/delivery-claim",
            "description": "Atomically claim the next failed or stale prepared escalation notification for leased worker delivery.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.inbox.notification.delivery_claim.renew",
            "method": "POST",
            "path": "/agents/action-queues/tasks/escalations/inbox/notification/delivery-claim/{notification_id}/renew",
            "description": "Renew an active escalation notification delivery lease with claim-token validation.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.inbox.notification.delivery_claim.release",
            "method": "POST",
            "path": "/agents/action-queues/tasks/escalations/inbox/notification/delivery-claim/{notification_id}/release",
            "description": "Release a claimed escalation notification delivery lease with claim-token validation so it can be retried without a false attempt record.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.inbox.notification.delivery_claim.complete",
            "method": "POST",
            "path": "/agents/action-queues/tasks/escalations/inbox/notification/delivery-claim/{notification_id}/complete",
            "description": "Complete a leased escalation notification delivery attempt with claim-token validation, retry backoff, and max-attempt exhaustion.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.inbox.notification.logs.update",
            "method": "PATCH",
            "path": "/agents/action-queues/tasks/escalations/inbox/notification/logs/{notification_id}",
            "description": "Update escalation inbox notification delivery status, delivery timestamp, and delivery notes.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations",
            "method": "GET",
            "path": "/agents/action-queues/tasks/escalations",
            "description": "List saved advisor action queue tasks that need manager attention, with escalation reason and severity metadata.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.reviews",
            "method": "GET",
            "path": "/agents/action-queues/tasks/escalations/reviews",
            "description": "Read manager review history for saved advisor action queue task escalations.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalations.bulk_review",
            "method": "POST",
            "path": "/agents/action-queues/tasks/escalations/reviews",
            "description": "Bulk record manager escalation reviews for multiple saved advisor action queue tasks in one audited operation.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.escalation_review",
            "method": "POST",
            "path": "/agents/action-queues/{queue_id}/tasks/{task_id}/escalation-review",
            "description": "Record a manager acknowledgement, snooze, follow-up request, or resolution for an escalated saved queue task.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.bulk_update",
            "method": "PATCH",
            "path": "/agents/action-queues/tasks",
            "description": "Bulk update saved advisor action queue task status, notes, assignee, and due date across one or more queues for dashboard triage.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues.tasks.activity",
            "method": "GET",
            "path": "/agents/action-queues/tasks/activity",
            "description": "Read saved advisor action queue task status, notes, assignee, and due-date update history for audit and compliance review.",
        },
        {
            "router": "agents",
            "name": "agents.action_queues",
            "method": "GET",
            "path": "/agents/action-queues",
            "description": "List saved advisor action queues for an owner.",
        },
        {
            "router": "agents",
            "name": "agents.action_queue.show",
            "method": "GET",
            "path": "/agents/action-queues/{queue_id}",
            "description": "Fetch a saved advisor action queue with task status and evidence.",
        },
        {
            "router": "agents",
            "name": "agents.action_queue.update_task",
            "method": "PATCH",
            "path": "/agents/action-queues/{queue_id}/tasks/{task_id}",
            "description": "Update a saved advisor action queue task status or notes.",
        },
        {
            "router": "agents",
            "name": "agents.advisor_followup",
            "method": "POST",
            "path": "/agents/advisor-followup",
            "description": "Convert an owner morning brief into customer-ready follow-up copy and advisor guardrails.",
        },
        {
            "router": "agents",
            "name": "agents.morning_brief",
            "method": "POST",
            "path": "/agents/morning-brief",
            "description": "Prioritize customer actions across portfolios, watchlists, screeners, and freshness.",
        },
        {
            "router": "agents",
            "name": "agents.screener_copilot",
            "method": "POST",
            "path": "/agents/screener-copilot",
            "description": "Turn a customer stock-discovery idea into a structured screen with explained matches.",
        },
        {
            "router": "agents",
            "name": "agents.portfolio_digest",
            "method": "POST",
            "path": "/agents/portfolio-digest/{portfolio_id}",
            "description": "Generate a customer-level portfolio digest with cited evidence and next actions.",
        },
        {
            "router": "agents",
            "name": "agents.watchlist_digest",
            "method": "POST",
            "path": "/agents/watchlist-digest/{watchlist_id}",
            "description": "Generate a customer-level watchlist digest with cited evidence and alert context.",
        },
        {
            "router": "agents",
            "name": "agents.screener_digest",
            "method": "POST",
            "path": "/agents/screener-digest/{screener_id}",
            "description": "Generate a customer-level screener digest with cited evidence and next actions.",
        },
        {
            "router": "agents",
            "name": "agents.research_brief",
            "method": "POST",
            "path": "/agents/research-brief/{ticker}",
            "description": "Generate a cited AI research brief from local market and semantic evidence.",
        },
        {
            "router": "agents",
            "name": "agents.context",
            "method": "GET",
            "path": "/agents/context/{ticker}",
            "description": "Return a prompt payload for an analyst or execution agent.",
        },
        {
            "router": "agents",
            "name": "agents.workflow",
            "method": "GET",
            "path": "/agents/workflow/{ticker}",
            "description": "Return a recommended multi-step workflow for an agent to follow.",
        },
    ]
    return {
        "name": profile["title"],
        "description": profile["description"],
        "profile": profile["name"],
        "openapi_url": f"{base_url}{request.app.openapi_url}",
        "capabilities_url": f"{base_url}/capabilities",
        "tools": [
            {key: value for key, value in tool.items() if key != "router"}
            for tool in tool_catalog
            if tool["router"] in active_routers
        ],
    }
